# Generated by Django 2.2.4 on 2020-11-11 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_by', models.ManyToManyField(related_name='favorite_books', to='login.User')),
                ('uploaded_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='books_uploaded', to='login.User')),
            ],
        ),
    ]
