# Generated by Django 2.2.4 on 2020-11-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authers',
            new_name='authors',
        ),
    ]
